### ISSUE TITLE
Missing TypeScript types in latest version

### ISSUE THREAD

**Issue by travishorn** [travishorn/connect-lowdb#3]
This library was recently updated to be compatible with the latest versions of lowdb. As lowdb's API has changed, I believe the work that @KeithBrown39423 did to add the type declaration is no longer compatible in this version (at least, I was getting TypeScript errors).

I'm not experienced enough with TypeScript to update the declaration file. In the meantime, I removed the now incorrect `index.d.ts` and the `types` property in `package.json`.

**Comment by KeithBrown39423** [comment]
I'll can work on fixing this later this week.

**Comment by KeithBrown39423** [comment]
After reviewing the changes made, the typescript code shouldn't change. Everything should still work the same.

**Comment by KeithBrown39423** [comment]
I tested this and everything is working
